### ISSUE TITLE
As a user I would like the code to be displayed by default

### ISSUE THREAD

**Issue by ALanguillaume** [ThinkR-open/quakr#2]
## Validation

- [ ] Any new slide deck written using quakr will by default display code 

Rendering this qmd file :

![image](https://github.com/ThinkR-open/quakr/assets/54443785/9f3baa96-916e-424a-8bf1-6152b2d94d3a)

Yields this slide :

![image](https://github.com/ThinkR-open/quakr/assets/54443785/d0f10ed6-2fe4-48f5-b7cf-6a69a9fd05cd)

## Technical

``` yaml
title: thinkridentity
author: ThinkR-open
version: 1.0.0
quarto-required: ">=1.3.0"
contributes:
  formats:
    revealjs:
      slideNumber: true
      theme: [default, thinkridentity.scss]
      logo: logo.png
      footer: |
        **<i class="las la-book"></i> {{< meta title >}}** |
        Retrouvez nous sur <https://thinkr.fr>
      title-slide-attributes:
        data-background-image: background.png
      code-annotations: hover
      chalkboard: true
      # HERE (this comment is to be removed)
      execute:
        echo: true
```
